---
- name: test connection
  action: shell echo 'hello world'

# needs the reboot command below to not allow kodi to save in-ram setitng to disk
- name: set guisettings.xml
  replace:
    path: /home/osmc/.kodi/userdata/guisettings.xml
    regexp: '^(.*)<{{ item.tag }}.*>.*</{{ item.tag }}>$'
    replace: '\1<{{ item.tag }}>{{ item.value }}</{{ item.tag }}>'
    backup: yes
  with_items:
    - { tag: 'skin', value: 'skin.estuary' }
    - { tag: 'settinglevel', value: '3' }
    - { tag: 'seeksteps', value: '-60,-30,-10,10,30,60' }
  tags: test

- name: disable used main menu items
  replace:
    path: /home/osmc/.kodi/userdata/addon_data/skin.estuary/settings.xml
    regexp: '^(.*)<setting id="{{ item }}" type="bool">.*</setting>$'
    replace: '\1<setting id="{{ item }}" type="bool">true</setting>'
    backup: yes
  with_items:
      - HomeMenuNoWeatherButton
      - HomeMenuNoMusicButton
      - HomeMenuNoMusicVideoButton
      - HomeMenuNoPicturesButton
      - HomeMenuNoRadioButton
      - HomeMenuNoVideosButton
      - HomeMenuNoProgramsButton

- name: reboot osmc
  command: /sbin/reboot
  ignore_errors: yes
