---
- name: Fix sudoers
  file: path=/etc/sudoers.d/osmc-no-secure-path state=absent
  become: true
  become_user: root
  become_method: sudo

- name: install apt-get dependencies
  apt: name={{ item }} force=yes
  with_items:
      - python-lxml
  become: true
  become_user: root
  become_method: sudo

- name: set skin to Estuary
  xml:
    path: /home/osmc/.kodi/userdata/guisettings.xml
    xpath: /settings/lookandfeel/skin
    value: skin.estuary

- name: remove the default attribute from skin setting
  xml:
    path: /home/osmc/.kodi/userdata/guisettings.xml
    xpath: /settings/lookandfeel/skin/@default
    state: absent

- name: set video seeksteps
  xml:
    path: /home/osmc/.kodi/userdata/guisettings.xml
    xpath: /settings/videoplayer/seeksteps
    value: -60,-30,-10,10,30,60

- name: set settings level to expert
  xml:
    path: /home/osmc/.kodi/userdata/guisettings.xml
    xpath: /settings/general/settinglevel
    value: 3

- name: disable used main menu items
  replace:
    path: /home/osmc/.kodi/userdata/addon_data/skin.estuary/settings.xml
    regexp: '^(.*)<setting id="{{ item }}" type="bool">.*</setting>$'
    replace: '\1<setting id="{{ item }}" type="bool">true</setting>'
    backup: yes
  with_items:
      - HomeMenuNoWeatherButton
      - HomeMenuNoMusicButton
      - HomeMenuNoMusicVideoButton
      - HomeMenuNoPicturesButton
      - HomeMenuNoRadioButton
      - HomeMenuNoVideosButton
      - HomeMenuNoProgramsButton

# needs the reboot command to not allow kodi to overwrite with in-ram setitng
- name: reboot osmc
  command: /sbin/reboot
  ignore_errors: yes
